CREATE DATABASE appUsuarios;

USE appUsuarios;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  correo VARCHAR(100) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL
);


CREATE TABLE reportes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    latitud DECIMAL(10, 8) NOT NULL,
    longitud DECIMAL(11, 8) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

ALTER TABLE reportes MODIFY COLUMN nivel VARCHAR(10);
ALTER TABLE usuarios ADD COLUMN expo_push_token VARCHAR(255);